[project]
name = "purchasing-agents"
version = "0.1.0"
description = "A collection of purchasing agents that can help with customer enquiries"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.5.0",
]
