name: Release MCP Tools

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: ./crm-erp-mcp-tools
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}